### PR TITLE
producer&partition info in topic page nsqadmin

### PR DESCRIPTION
**Pull request by DoraALin**
wechatimg5091

### CODE REVIEW

**Comment by DoraALin** [comment]
1. topic statstic info added in topic page.
2. message  count & total depth info in statistics page

**Comment by absolute8511** [comment]
@DoraALin 
1. HourlyPubSize should not in the TopicCoordStat struct (only used for distributed system stats).
2. Please rank by the recent hourly pub size not the total message count.
3. The hourly pub size means the recent hours not the 00:00~24:00

**Comment by DoraALin** [comment]
1.move message history out of topicCoordStats, to NSQDStats;
2.rank by latest hourly pub size;
3.adjust the description of hourly pub size;

**Comment by DoraALin** [comment]
wechatimg5144

**Review by absolute8511 — APPROVED** [review]
LGTM

**Pull request merged**
